### ISSUE TITLE
Enable grid overrides to use number inputs

### ISSUE THREAD

**Issue by odjuricicTT** [madcampos/model-explorer#1]
For overriding grid size of a node we want to be able to input numbers instead of choosing from a bunch of options. A grid is represented by two numbers X and Y where both fall within some rage that the server can provide with the editable key value pair.
e.g. 1x64 and 8x8 are valid grids.

**Comment by madcampos** [comment]
We do have a type for a "list of integers" here:
https://github.com/madcampos/model-explorer/blob/b25bce9e6bab7a6e71483ebee602f9955f3a8965/src/ui/src/components/visualizer/common/input_graph.ts#L154-L161

The size parameters specify how many items will be on the list, for example, a list with 3 integers.

The range parameters are the range each number falls into, for example: between 1 to 100.

The step parameter is how large to move each time, for example, a step of 8 means it goes like this: 8, 16, 24, 32, etc.

Would that work or be almost what you are looking for?

**Comment by madcampos** [comment]
Moved to: https://github.com/tenstorrent/model-explorer/issues/3
